Expose from_pretrained keyword arguments
allenai/allennlp pull request #4651
Opened 2020-09-18 14:56 UTC by mulhod

Addresses #4650 

I'd like to get feedback about whether or not this change is reasonable/something you would consider merging. It is not finished yet. I did add a simple test just to demonstrate how it would work. I also tested `Predictor.from_path` locally with a model of my own based on `"bert-base-uncased"`.

2020-09-18 22:22 UTC, epwalsh requested changes
Hey @mulhod, I think this would be good to have, but I don't think we should add this argument to `Model.load`, `load_archive`, or `Predictor.from_path` since this is something that is specific to transformers, and you could just use the `overrides` argument to these functions in order to utilize this feature.

2020-09-18 22:22 UTC, epwalsh commented on allennlp/common/cached_transformers.py
> +    from_pretrained_kwargs: Optional[Dict[str, Any]] = None,
I think we should just call this `**kwargs`.

2020-09-21 17:52 UTC, mulhod commented
I have revised the way it was being done to use `overrides` (which wasn't in `Predictor.from_path` -- I added it in).

I fear that this is still too complicated, but it appears to work. While I don't have a test for `Predictor.from_path`, I have tried that locally:
```
from json import dumps
from pathlib import Path

import ets_nlp_allennlp_models  # Internal package
from allennlp.predictors import Predictor

kwargs = {
    "transformers_from_pretrained_kwargs":
        {
            "local_files_only": True,
            "cache_dir": "/my/custom/location/for/torch/transformers"
        }
}

archive_path = Path("ets-nlp-allennlp-models/test_fixtures/models/general_regressor/model.tar.gz")
predictor = Predictor.from_path(archive_path, overrides=dumps(kwargs))
```

When the cache dir I pass in is empty/non-existent and `local_files_only` is `True`, this leads to the expected error. When present, the local files are used in that directory as opposed to the default location for the cache.

I would be happy to work on some more tests for this.

2020-09-21 18:02 UTC, mulhod commented
I see the build failed in relation a formatting issue (easy fix) and a documentation issue (I added a `Path` type hint to the archive file parameter since it actually accepts a `Path` argument or a `str` argument. In any case, that is not related to this PR and can be taken out. It seemed like a small improvement to make. In any case, the tests pass otherwise, so I will hold off on that.

2020-09-21 18:39 UTC, epwalsh requested changes
Hey @mulhod, sorry my initial comments were confusing. What I meant was that `cached_transformers.get()` should directly pass `**kwargs` to `AutoModel.from_pretrained()`, just like how `cached_transformers.get_tokenizer()` does.

I left some other suggestions for making the rest of the PR work with this.

2020-09-21 18:39 UTC, epwalsh commented on allennlp/common/cached_transformers.py
> +                **kwargs.get("transformers_from_pretrained_kwargs", {}),
```suggestion
                **kwargs,
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/common/cached_transformers.py
> +                **kwargs.get("transformers_from_pretrained_kwargs", {}),
```suggestion
                **kwargs,
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/common/from_params.py
> +            ]
I don't think this is necessary

```suggestion
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/models/archival.py
> +    archive_file : `str`/`Path`
```suggestion
    archive_file : `Union[str, Path]`
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/models/model.py
> +            ].as_dict()
Shouldn't need this

```suggestion
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/models/model.py
> +        )
Shouldn't need this either

```suggestion
        model = Model.from_params(vocab=vocab, params=model_params)
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/predictors/predictor.py
> +        archive_path : `str`/`Path`
```suggestion
        archive_path : `Union[str, Path]`
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/modules/token_embedders/pretrained_transformer_embedder.py
> +        **kwargs,
```suggestion
        tokenizer_kwargs: Optional[Dict[str, Any]] = None,
        transformer_kwargs: Optional[Dict[str, Any]] = None,
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/modules/token_embedders/pretrained_transformer_embedder.py
> +            **kwargs,
```suggestion
            **(transformer_kwargs or {}),
```

2020-09-21 18:39 UTC, epwalsh commented on allennlp/modules/token_embedders/pretrained_transformer_embedder.py
> +            tokenizer_kwargs=kwargs.get("transformers_from_pretrained_kwargs", {}),
```suggestion
            tokenizer_kwargs=tokenizer_kwargs,
```

2020-09-21 21:59 UTC, mulhod commented
Thanks for the help @epwalsh. I applied your suggestions locally first to do some testing. While the tests I added pass (at least they did locally, not sure what the failure is yet), the arguments I'm passing through via `overrides` in `Predictor.from_path` are still not actually being passed through to `from_pretrained`. I set a breakpoint before all `from_pretrained` calls so that I can inspect the arguments and I don't see those I specified via `overrides`. I'm not sure what the issue is, but will look into it some more.

2020-09-21 22:45 UTC, epwalsh commented
@mulhod can you show me what you're passing to `overrides`?

2020-09-21 22:47 UTC, epwalsh commented on CHANGELOG.md
> +- Added ability to pass `transformers`-related keyword arguments through to `from_pretrained` via `overrides`.
```suggestion
- Added ability to pass additional key word arguments to `cached_transformers.get()`, which will be passed on to `AutoModel.from_pretrained()`.
- Added an `overrides` argument to `Predictor.from_path()`.
```

2020-09-22 04:08 UTC, mulhod commented
@epwalsh I have made some more changes and was able to get it to work locally. I was using `overrides` incorrectly for one thing and that was my main problem. But I made some changes to my model code and some to this PR and was able to get the behavior I was interested in. This is the little test script that I was using:
```
from json import dumps
from pathlib import Path

import ets_nlp_allennlp_models  # internal ETS package
from allennlp.predictors import Predictor

kwargs = {
    "model.text_field_embedder.token_embedders.tokens": {
        "tokenizer_kwargs": {
            "local_files_only": True,
            "cache_dir": "/Users/mmulholland/.cache/torch/transformers"
        },
        "transformer_kwargs": {
            "local_files_only": True,
            "cache_dir": "/Users/mmulholland/.cache/torch/transformers"
        }
    },
    "model.seq2vec_encoder": {
        "transformer_kwargs": {
            "local_files_only": True,
            "cache_dir": "/Users/mmulholland/.cache/torch/transformers"
        }
    },
    "dataset_reader": {
        "tokenizer_kwargs": {
            "local_files_only": True,
            "cache_dir": "/Users/mmulholland/.cache/torch/transformers"
        },
        "transformer_kwargs": {
            "local_files_only": True,
            "cache_dir": "/Users/mmulholland/.cache/torch/transformers"
        }
    }
}

archive_path = Path("ets-nlp-allennlp-models/test_fixtures/models/general_regressor/model.tar.gz")
predictor = Predictor.from_path(archive_path, overrides=dumps(kwargs))
```

When `/Users/mmulholland/.cache/torch/transformers` has the cache files I need, the model loads correctly. When I move that directory to `/Users/mmulholland/.cache/torch/transformers.bak` and run the script again, it then fails to find the cache files, as expected.

2020-09-22 04:17 UTC, mulhod commented on allennlp/modules/seq2vec_encoders/bert_pooler.py
> +        for `AutoTokenizer.from_pretrained`.
```suggestion
        for `AutoModel.from_pretrained`.
```

2020-09-22 17:00 UTC, epwalsh requested changes
@mulhod thank you, this looks really good!

I just had a few minor comments. If you can fix those up we'll get this merged 🎉 

As a side note, I feel like the `overrides` argument throughout the library should accept a JSON string or a Python dictionary. That would make it much easier to use from Python directly. What do you think?

2020-09-22 17:10 UTC, mulhod commented
Thanks for the suggestions. I'll take care of the tests stuff.

> As a side note, I feel like the `overrides` argument throughout the library should accept a JSON string or a Python dictionary. That would make it much easier to use from Python directly. What do you think?

Yes, this would be great and probably a pretty easy change. Should it be taken care of here?

2020-09-22 17:14 UTC, epwalsh commented
> Yes, this would be great and probably a pretty easy change. Should it be taken care of here?

I think that would be best as a separate PR. Feel free to assign me as a reviewer if you want to take that on.

2020-09-22 17:37 UTC, epwalsh approved these changes
LGTM!

2020-09-22 17:39 UTC, merged