Allow usage of .tar.gz with PretrainedModelInitializer
allenai/allennlp pull request #4709
Opened 2020-10-06 21:02 UTC by eladsegal

2020-10-07 16:35 UTC, dirkgr commented
This is a nice feature, but there is quite a bit of overlap with what `cached_path()`'s "`extract_archive`" feature already does. Is there a way we can just use `cached_path()`? It will extract the archive into the cache directory, which means it needs no cleanup, and therefore no context manager.

2020-10-07 16:51 UTC, eladsegal commented
> This is a nice feature, but there is quite a bit of overlap with what `cached_path()`'s "`extract_archive`" feature already does. Is there a way we can just use `cached_path()`? It will extract the archive into the cache directory, which means it needs no cleanup, and therefore no context manager.

Personally I'm ok with no cleanup, but see these recent issue and the corresponding pull request - https://github.com/allenai/allennlp/issues/4642, https://github.com/allenai/allennlp/pull/4643.

2020-10-08 18:52 UTC, dirkgr requested changes
The big issue is that `load_archive_contextmanager()` doesn't make sense in its current form. At least, I don't see it. Why do we need it?

The other comments are details.

2020-10-08 18:52 UTC, dirkgr commented on tests/nn/pretrained_model_initializer_test.py
> +            os.remove(temp_tar_gz)
Why not `with tempfile.NamedTemporaryFile(...):`?

This is an excellent place for a context manager :-)

2020-10-08 19:24 UTC, eladsegal commented
> The big issue is that `load_archive_contextmanager()` doesn't make sense in its current form. At least, I don't see it. Why do we need it?
> 
> The other comments are details.

Hi @dirkgr, indeed using contextmanager doesn't make sense for this pull request.
I worked on multiple changes that were split across multiple pull request, so this change was made with another pull request in mind - https://github.com/allenai/allennlp/pull/4713.
When extracting an archive for the `evaluate` or `predict` commands, passing the extraction directory as serialization_dir to the model/dataset reader constructor must be done before the extraction directory is deleted - this is the justification I saw for contextmanager.
It is also why I return `archive, serialization_dir` from `load_archive_contextmanager`.
I could have returned only `archive` and add `extraction_path/serialization_dir` as a member in it, but it made less sense to me to have a member that holds an already deleted path.

Example of the usage:
https://github.com/allenai/allennlp/blob/8a8451d6c1120b543cc7ec1b2860c3dc154131c9/allennlp/commands/evaluate.py#L120-L139

2020-10-08 19:26 UTC, eladsegal commented on allennlp/models/archival.py
> +        yield archive, serialization_dir
I agree, I don't like it too.
The issue is that archive is indeed valid afterwards, but serialization_dir is not.
I'll try to think how to split it in a cleaner way

2020-10-08 23:21 UTC, dirkgr commented
Can you solve that scenario with something like this?
```Python
with extracted_archive(...) as d:
   archive = load_archive(d)
  do_other_stuff_with(d)
```

In your example, you do this because you want to pass the serialization directory to the reader. Can we make the reader part of `Archive` instead so that problem goes away?

I have a question open on the other PR about why the reader needs the archive in the first place.

2020-10-08 23:40 UTC, eladsegal commented
> Can you solve that scenario with something like this?
> 
> ```python
> with extracted_archive(...) as d:
>    archive = load_archive(d)
>    do_other_stuff_with(d)
> ```
That's exactly what I did in the the other pull request :)

> 
> In your example, you do this because you want to pass the serialization directory to the reader. Can we make the reader part of `Archive` instead so that problem goes away?
>
You are right, it will solve the problem, and I think it is also reasonable to include the dataset reader object when loading an archive.
I'll make the change, Archive object will have two new fields: `dataset_reader` and `validation_dataset_reader` (so `Predictor` will be able to select `dataset_reader_to_load`).

2020-10-09 21:39 UTC, eladsegal commented
@dirkgr I've made the requested changes

2020-10-10 00:00 UTC, dirkgr approved these changes
I have some comments, but it also looks good as it is. Let me know if you want to change something, otherwise I'll hit the merge button. Thank you for this one (and the other ones, including the ones still pending).

2020-10-10 01:55 UTC, eladsegal commented on tests/models/archival_test.py
> +                "trainer": {"num_epochs": 2, "optimizer": "adam", "cuda_device": -1},
When running on a machine without a GPU, the test will pass. However, on a machine with GPU, the trainer will automatically set `cuda_device` to 0 ([here](https://github.com/allenai/allennlp/blob/3a85e3595b71c05fbd9acb014e3d76b5b7dd0bc4/allennlp/training/trainer.py#L56-L62)) and the returned model will be on the GPU while the model from the archive will be on the CPU.

2020-10-10 03:16 UTC, eladsegal commented
> I have some comments, but it also looks good as it is. Let me know if you want to change something, otherwise I'll hit the merge button. Thank you for this one (and the other ones, including the ones still pending)!

I've made the validation dataset reader, ready for merge.
And you are welcome, I'm happy to contribute!

2020-10-15 11:04 UTC, eladsegal commented
Hi @dirkgr, can we merge this?

2020-10-16 00:43 UTC, dirkgr commented
@eladsegal, yes, we can. I'm going on vacation beginning tomorrow. For the next two weeks, can you ping @epwalsh if there are things I forgot to take care of?

2020-10-16 00:50 UTC, merged