Trainer/serialization dir
allenai/allennlp pull request #4940
Opened 2021-01-28 15:41 UTC by himkt

Background: https://github.com/allenai/allennlp/issues/4939

`GradientDescentTrainer` makes `serialization_dir` itself.

@epwalsh Please take a look.

2021-01-28 16:09 UTC, epwalsh commented on CHANGELOG.md
> +- GradientDescentTrainer makes `serialization_dir` in its instantiated step.
```suggestion
- GradientDescentTrainer makes `serialization_dir` when it's instantiated, if it doesn't exist.
```

2021-01-28 16:09 UTC, epwalsh commented on CHANGELOG.md
> +- GradientDescentTrainer makes `serialization_dir` in its instantiated step.
Could you move this up to the "Unreleased" section?

2021-01-29 01:07 UTC, himkt commented
@epwalsh Thank you for the quick review. I revised the PR. PTAL.

2021-01-29 17:27 UTC, epwalsh commented on CHANGELOG.md
> +- GradientDescentTrainer makes `serialization_dir` when it's instantiated, if it doesn't exist.
```suggestion
### Changed

- GradientDescentTrainer makes `serialization_dir` when it's instantiated, if it doesn't exist.
```

2021-01-29 17:31 UTC, epwalsh requested changes

2021-01-29 17:31 UTC, epwalsh commented on allennlp/training/trainer.py
> +            os.makedirs(serialization_dir, exist_ok=True)
So if `checkpointer` is not `None` we might still not create the serialization directory? I think we want to create it either way, right?

2021-01-29 21:15 UTC, epwalsh commented on allennlp/training/trainer.py
> +
```suggestion

```

2021-01-29 21:26 UTC, epwalsh approved these changes
Thanks @himkt! I just made one little change so that the serialization directory is actually created in the base `Trainer` class.

2021-01-29 21:31 UTC, merged