Add text_key and label_key to TextClassificationJsonReader
allenai/allennlp pull request #5005
Opened 2021-02-21 05:47 UTC by RyujiTamaki

Fixes #4636 .

Changes proposed in this pull request:

- Add `text_key` and `label_key` to `TextClassificationJsonReader`.
- Add `test_fixtures/data/text_classification_json/ag_news_corpus_test_key_name.jsonl` for test.
- Add test.

2021-02-22 17:31 UTC, epwalsh requested changes
Thanks @RyujiTamaki! This looks good. I just have a few comments:

I actually don't think the test case you added is necessary. The existing tests should already cover your changes. Could you please remove that and look at the two other suggestions I made? Then we'll get this merged.

2021-02-22 17:31 UTC, epwalsh commented on allennlp/data/dataset_readers/text_classification_json.py
> +        key name for LabelField instance in JSON.
```suggestion
    text_key: `str`, optional (default=`"text"`)
        The key name of the source field in the JSON data file.
    label_key: `str`, optional (default=`"label"`)
        The key name of the target field in the JSON data file.
```

2021-02-22 17:31 UTC, epwalsh commented on CHANGELOG.md
> +- Added `text_key` and `label_key` to `TextClassificationJsonReader` class.
```suggestion
- Added `text_key` and `label_key` parameters to `TextClassificationJsonReader` class.
```

2021-02-23 01:53 UTC, RyujiTamaki commented
@epwalsh
Thank you for reviewing! I fixed it.
But the CI has failed. It doesn't seem to have anything to do with my fix. Could you check it?
I cannot find the way to solve that.

2021-02-23 03:00 UTC, epwalsh commented
@RyujiTamaki ah yeup, looks like our GPU CI server was having issues. I just restarted it.

2021-02-23 03:01 UTC, epwalsh approved these changes
LGTM! Thanks @RyujiTamaki!

2021-02-23 17:47 UTC, merged