Refactor span extractors and unify forward.
allenai/allennlp pull request #5160
Opened 2021-04-27 13:13 UTC by izhx

Fixes #5145.

Changes proposed in this pull request:

- added the `__init__` method to `SpanExtractor` for initiating `span_width_embedding` and other attributes.
- added the `forward` method to `SpanExtractor` to unify `forward` arguments of all extractors. 
- added comments for `width = span_end - span_start`.
- added an `_embed_spans` method, which need to be implemented to compute span embeddings in different ways,  to `SpanExtractor`.
- modified `EndpointSpanExtractor`, `SelfAttentiveSpanExtractor` and `BidirectionalEndpointSpanExtractor` accordingly (change `forward` to `_embed_spans`).

2021-04-27 17:36 UTC, ArjunSubramonian reviewed
This personally looks great to me! Thanks for refactoring. I'm adding @dirkgr to look it over as well.

2021-04-27 20:47 UTC, dirkgr requested changes
I would like to keep `SpanExtractor` as a purely abstract base class, just in case someone wants to build a totally different span extractor. But it makes sense to have a `SpanExtractorWithSpanWidthEmbedding` class that's basically the class you wrote, and have all the concrete implementations derive from that (the way you already have it). Does that make sense?

Thanks for finding and fixing this!

2021-04-27 20:47 UTC, dirkgr commented on allennlp/modules/span_extractors/span_extractor.py
> +            # But here we do not add 1 beacuse we offen initiate the span width
Typo

2021-04-28 08:25 UTC, izhx commented
> I would like to keep `SpanExtractor` as a purely abstract base class, just in case someone wants to build a totally different span extractor. But it makes sense to have a `SpanExtractorWithSpanWidthEmbedding` class that's basically the class you wrote, and have all the concrete implementations derive from that (the way you already have it). Does that make sense?
> 
> Thanks for finding and fixing this!

Yeah, I totally agree with you! It's going to be flexible for future developments. 
I have made these changes, Thanks!

2021-04-28 08:27 UTC, izhx commented on allennlp/modules/span_extractors/span_extractor.py
> +            # But here we do not add 1 beacuse we offen initiate the span width
Changed `offen` to `often `. 🤣

2021-04-28 17:52 UTC, ArjunSubramonian commented
> > I would like to keep `SpanExtractor` as a purely abstract base class, just in case someone wants to build a totally different span extractor. But it makes sense to have a `SpanExtractorWithSpanWidthEmbedding` class that's basically the class you wrote, and have all the concrete implementations derive from that (the way you already have it). Does that make sense?
> > Thanks for finding and fixing this!
> 
> Yeah, I totally agree with you! It's going to be flexible for future developments.
> I have made these changes, Thanks!

@izhx Thanks for your great work! The changes look fine to me. I would edit the description of the PR to reflect what you reverted. Also, as a heads up, @dirkgr is out the rest of this week, so please give us a week to get back to you.

2021-04-29 15:06 UTC, izhx commented
> > > I would like to keep `SpanExtractor` as a purely abstract base class, just in case someone wants to build a totally different span extractor. But it makes sense to have a `SpanExtractorWithSpanWidthEmbedding` class that's basically the class you wrote, and have all the concrete implementations derive from that (the way you already have it). Does that make sense?
> > > Thanks for finding and fixing this!
> > 
> > 
> > Yeah, I totally agree with you! It's going to be flexible for future developments.
> > I have made these changes, Thanks!
> 
> @izhx Thanks for your great work! The changes look fine to me. I would edit the description of the PR to reflect what you reverted. Also, as a heads up, @dirkgr is out the rest of this week, so please give us a week to get back to you.

Thank you! 😄

2021-05-03 18:29 UTC, dirkgr approved these changes
Thank you!

2021-05-03 18:43 UTC, merged