Added `DataCollator` for dynamic operations for each batch.
allenai/allennlp pull request #5221
Opened 2021-05-25 09:49 UTC by wlhgtc

related to #5218

2021-05-25 09:55 UTC, wlhgtc commented
@epwalsh  I finish the demo version of the `DataCollator`.
The input type is different between ours and Transformers. So I didn't inherit the whole class. Just use some functions.
And one tiny problem: I got `{"tokens":{"tokens":{"input_ids"}}}` tensors, but I am not sure where the two "tokens" come from. 
It's a better way to set them as parameters ? The code could be found in [here](https://github.com/allenai/allennlp/pull/5221/commits/18c35b615747c556ced1627a29ffe1f2b289e63c#diff-3d369352a01b4fca7472eeda3d17fbf4730b637fb7ef65c8746906969ea5d6a7R66).

2021-05-25 18:35 UTC, epwalsh reviewed
Looks good!

Could you fix the failing test, and also add a test for the `LanguageModelingDataCollator`?

2021-05-25 18:35 UTC, epwalsh commented on allennlp/data/data_loaders/data_collator.py
> +    def process_tokens(self, tensor_dicts: TensorDict) -> Tuple[torch.Tensor, torch.Tensor]:
?

```suggestion
    def process_tokens(self, tensor_dicts: TensorDict) -> TensorDict:
```

2021-05-25 18:35 UTC, epwalsh commented on CHANGELOG.md
> +### Added
There's already an "Added" section below.

2021-05-26 00:54 UTC, dirkgr reviewed
The collator seems like a really weird place to do things like this, but if that's how huggingface does it, we shouldn't be different just for the sake of being different.

I'll leave final approval to @epwalsh.

2021-05-26 01:22 UTC, wlhgtc commented
> The collator seems like a really weird place to do things like this, but if that's how huggingface does it, we shouldn't be different just for the sake of being different.
> 
> I'll leave final approval to @epwalsh.

It's the only way that could do some dynamic operations for different batch.
 We cached each instance in `Dataloader`, so we can not do it before instance.

2021-05-26 17:37 UTC, dirkgr commented
> It's the only way that could do some dynamic operations for different batch.

It would make more sense to me to write a data loader that has the ability to modify instances before they are being batched. We could give the data loader a callback to do just that. That makes more sense than abusing a function that's meant to just construct batches. But like I said, let's just stick to what huggingface does, so people aren't surprised when they encounter our API.

2021-05-26 20:02 UTC, dirkgr requested changes
This is great, thanks for doing it! I just have some minor requests about how to use `Registrable`.

2021-05-26 20:02 UTC, dirkgr commented on allennlp/data/data_loaders/data_collator.py
> +@DataCollator.register("language-model")
```suggestion
@DataCollator.register("language_model")
```

We should be using underscores for everything. It's annoying when you have to check which one it is while writing a config file.

The only exceptions I can think of are commands and vocabularies. For commands, I kind of get it. Commands on the command line usually use dashes. For vocabularies we also use dashes, which I think is wrong, but I don't want to break backwards compatibility for it.

2021-05-27 18:20 UTC, dirkgr approved these changes
Thank you!

2021-05-27 18:37 UTC, merged