added BackwardCallback
allenai/allennlp pull request #5249
Opened 2021-06-09 20:07 UTC by ArjunSubramonian

Additions proposed in this pull request:
- Added `BackwardCallback`, a training callback which allows for control over backpropagation and gradient manipulation.

2021-06-09 22:53 UTC, dirkgr requested changes
I think this design is too heavy. I don't like putting a core functionality like `loss.backward()` into a callback. It makes it too hard to see what's going on in the trainer.

Instead, can we use the normal `TrainerCallback`, and give it some extra methods, like `pre_backward()` and `post_backward()`? Can you solve your problem with that?

2021-06-09 23:04 UTC, ArjunSubramonian commented
> I think this design is too heavy. I don't like putting a core functionality like `loss.backward()` into a callback. It makes it too hard to see what's going on in the trainer.
> 
> Instead, can we use the normal `TrainerCallback`, and give it some extra methods, like `pre_backward()` and `post_backward()`? Can you solve your problem with that?

I can't do adversarial training without `backward()` being called in a callback because I need to call `backward()` two times and one call requires `retain_graph=True`.

2021-06-09 23:17 UTC, dirkgr commented
You could leave one `backward()` call as it is, and issue the second one in the callback?

2021-06-10 16:23 UTC, ArjunSubramonian commented
> You could leave one `backward()` call as it is, and issue the second one in the callback?

@dirkgr I have made the revisions you suggested :)

2021-06-10 17:09 UTC, dirkgr approved these changes
Other than the changelog entry, this is great!

2021-06-10 17:09 UTC, dirkgr commented on CHANGELOG.md
> +- Added `BackwardCallback`, a training callback which allows for control over backpropagation and gradient manipulation.
This comment isn't accurate anymore, is it?

2021-06-10 17:09 UTC, dirkgr commented on allennlp/training/callbacks/backward.py
> +        return False
Is it an error if this gets called with `backward_called == True`? Should we throw an exception in that case?

2021-06-10 17:09 UTC, dirkgr commented on tests/training/trainer_test.py
> +                param.grad *= 0.0
Is that really the best way to do that?
```suggestion
                param.zero_()
```
I don't know for sure, but I would guess that `zero_()` is faster.

2021-06-10 23:16 UTC, dirkgr approved these changes
This is great! Will make a great update for tomorrow's meeting, too!

2021-06-11 00:04 UTC, merged