Remove broken version of PyTorch
allenai/allennlp pull request #5512
Opened 2021-12-15 16:40 UTC by dirkgr

2021-12-15 21:30 UTC, epwalsh requested changes

2021-12-15 21:30 UTC, epwalsh commented on CHANGELOG.md
> +- Removed broken version of PyTorch from the list of approved versions
How about something like:
```suggestion
- Removed support for PyTorch version 1.10.0 due to critical bugs that caused regressions in the performance of some of our models. See https://github.com/pytorch/pytorch/issues/67167 and https://github.com/pytorch/pytorch/issues/67239 for details.
```

2021-12-15 21:30 UTC, epwalsh commented on .github/workflows/ci.yml
> +            echo "DOCKER_IMAGE_NAME=allennlp/commit:${GITHUB_SHA}" >> $GITHUB_ENV;
Per our slack conversation I think it's important that we tag the image with the CUDA version.

2022-01-06 16:35 UTC, dirkgr commented
I'm giving up on this. Our system is so complicated, excluding a single version of PyTorch is outside our capabilities now.

2022-01-06 16:35 UTC, closed without merging