Add `custom_dummy_tokens` to `PretrainedTransformerTokenizer`
allenai/allennlp pull request #5608
Opened 2022-03-26 07:01 UTC by tarohi24

This commit aims to support #5597

Fixes # .

Changes proposed in this pull request:

-

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.
- [ ] **`codecov/patch`** reports high test coverage (at least 90%).
    You can find this under the "Actions" tab of the pull request once the other checks have finished.

2022-04-01 18:39 UTC, epwalsh requested changes
Thanks @tarohi24! This looks good, I just have two small suggestions

2022-04-01 18:39 UTC, epwalsh commented on CHANGELOG.md
> +- Added `custom_dummy_tokens` argument to `TestPretrainedTransformerTokenizer`.
```suggestion
### Added

- Added `custom_dummy_tokens` argument to `TestPretrainedTransformerTokenizer`.
```

2022-04-01 18:39 UTC, epwalsh commented on allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
> +        custom_dummy_tokens: Optional[Tuple[str, str]] = None,
How about calling this `verification_tokens` instead?
```suggestion
        verification_tokens: Optional[Tuple[str, str]] = None,
```

2022-04-01 23:34 UTC, tarohi24 commented
Thanks @epwalsh for reviewing! Both suggestions look good to me. I committed them.

2022-04-01 23:45 UTC, tarohi24 commented
Thanks, @epwalsh for reviewing! The suggestions look good to me. I made commits to reflect these suggestions.

2022-04-06 16:28 UTC, epwalsh approved these changes
LGTM! Thanks @tarohi24!

2022-04-06 23:42 UTC, epwalsh commented
Looks like we'll need to resolve https://github.com/allenai/allennlp/pull/5613 before merging this.

2022-04-08 00:37 UTC, merged